### ISSUE TITLE
Error at processing version

### ISSUE THREAD

**Issue by bmcilw1** [slamotte/vault2git#10]
There seems to be an error in the Processing version x of y, in one of the calls to the time library.

My ruby version:
ruby 1.9.3p551 (2014-11-13) [i386-mingw32]

Output:
 INFO vault2git: Starting at 2016-01-15 18:01:53 -0600
 INFO vault2git: Prepare destination folder
 INFO vault2git: Set Vault working folder
 INFO vault2git: Fetch version history
 INFO vault2git: Processing version 1 of 8
C:/Ruby193/lib/ruby/1.9.1/time.rb:202:in `local': argument out of range (ArgumentError)
        from C:/Ruby193/lib/ruby/1.9.1/time.rb:202:in `make_time'
        from C:/Ruby193/lib/ruby/1.9.1/time.rb:271:in `parse'
        from C:/Users/Brian/Documents/vault2git/converter.rb:143:in `block in convert'
        from C:/Users/Brian/Documents/vault2git/converter.rb:137:in `each'
        from C:/Users/Brian/Documents/vault2git/converter.rb:137:in `each_with_index'
        from C:/Users/Brian/Documents/vault2git/converter.rb:137:in `convert'
        from vault2git.rb:7:in `<main>'

**Comment by slamotte** [comment]
Try putting 

`info "Version date is {version[:date]}"` 

before line 143 and see what it contains. The problem is the `Time.format` does not recognize the version's date. If you don't care about keeping the original date in Git history then you can simply remove the `--date` argument from the commit command; it will still be in the commit comment.
